AllCops:
  Include:
    - '**/Gemfile'
    - Vagrantfile
    - Berksfile
    - Rakefile
    - metadata.rb
    - attributes/**/*
    - definitions/**/*
    - libraries/**/*
    - providers/**/*
    - recipes/**/*
    - resources/**/*
    - spec/**/*
    - test/**/*
  Exclude:
    - cookbooks/**/*
    - chef-repo/**/*
    - vendor/**/*
    - data/**/*

Style/ColonMethodCall:
  Exclude:
    - Vagrantfile

Metrics/MethodLength:
  Exclude:
    - targets/*.rb
    - instances/*.rb
    - lib/pentestenv/instance.rb
    - lib/pentestenv/customization.rb

Metrics/ClassLength:
  Exclude:
    - lib/pentestenv/customization.rb

Metrics/AbcSize:
  Exclude:
    - targets/*.rb
    - instances/*.rb
    - lib/pentestenv/customization.rb

Metrics/BlockLength:
  Exclude:
    - instances/*.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - instances/*.rb

Metrics/LineLength:
  Exclude:
    - instances/*.rb
    - targets/*.rb

Metrics/PerceivedComplexity:
  Exclude:
    - instances/*.rb

Style/FileName:
  Exclude:
    - /Vagrantfile
    - Berksfile
    - cookbook/Berksfile
    - targets/*.rb
    - instances/*.rb

Security/Eval:
  Exclude:
    - Berksfile
