language: ruby
dist: trusty
rvm:
  - 2.3.1

env:
  - VAGRANT_VERSION=1.8.5
  - VAGRANT_VERSION=2.0.0

install:
  - sudo apt-get update
  - sudo sudo apt-get -y install linux-headers-$(uname -r)
  - bundle install
  - wget http://download.virtualbox.org/virtualbox/5.1.6/virtualbox-5.1_5.1.6-110634~Ubuntu~trusty_amd64.deb -O vbox.deb
  - wget https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_x86_64.deb -O vagrant.deb
  - sudo dpkg -i vbox.deb
  - sudo dpkg -i vagrant.deb

before_script:
  - VBoxManage --version
  - vagrant --version

script:
  - bundle exec berks vendor
  - bundle exec rubocop -D
  - |
    for rc in examples/*; do
      echo Status for $rc
      PENTESTRC=$rc VAGRANT_LOG=debug vagrant status 2>vagrant.log; vcode=$?
      if test $vcode -ne 0; then
        echo " ERROR Pentest-env status error!" >&2
        echo "Logs:";cat vagrant.log;exit $vcode
      else
        echo "Logs:";grep -E "[A-Z]+ pentest-env/" vagrant.log;echo
      fi
    done
